= Документация проекта
Попов Николай
:toc: left
:toc-title: Содержание
:icons: font
= :source-highlighter: highlight._js_

== Краткое описание

Для корректной визуализации необходим плагин AsciiDoc

Рабочая директория: src/main/com.example.kafkalowlevel +
Контроллер для работы с сообщениями: <<KafkaController, /controller/KafkaController>> +
Java-класс продюсера: <<KafkaProducerService, /kafka/service/producer/KafkaProducerService.java>> +
Java-класс консьюмера Push: <<PushKafkaConsumerService, /kafka/service/consumer/PushKafkaConsumerService.java>> +
Java-класс консьюмера Pull: <<PullKafkaConsumerService, /kafka/service/consumer/PullKafkaConsumerService.java>> +
Java-класс для генерации тестовых сообщений: <<MessageGenerate, /kafka/utils/MessageGenerateService.java>>

== Классы и методы
[[KafkaController]] **KafkaController**: +
На вход принимает <<MessageDto, /kafkalowlevel/dto/MessageRequestDto.java>>
[source, java]

@PostMapping("/send")
public void sendMessage(@RequestBody MessageRequestDto request) {
    producer.sendMessage(request.getTopic(), request.getMessage());
}

[[KafkaProducerService]] **KafkaProducerService**: +
Продюсер для отправки сообщений.
[source, java]
public void sendMessage(String topic, Message message) {
    try {
        String serializedMessage = mapper.writeValueAsString(message);
        kafkaTemplate.send(topic, serializedMessage);
        log.info("В топик \"{}\" отправлено сообщение: {}", topic, serializedMessage);
    } catch (Exception e) {
        log.error("Не удалось отправить сообщение");
        throw new RuntimeException();
    }
}

[[PullKafkaConsumerService]] **PullKafkaConsumerService**: +
Пулл модель, коммитит по 5 сообщений. Активен со старта
[source, java]

public void consume() {
    // Подписка на топик
    List<String> topics = Collections.singletonList("my-topic");
    consumer.subscribe(topics);
    // Временное хранилище
    List<ConsumerRecord<String, String>> buffer = new ArrayList<>();
    int batchSize = 5;
    try {
        while (true) {
            // Ручной вызов poll для получения сообщений
            ConsumerRecords<String, String> records = consumer.poll(Duration.ofSeconds(5));
            for (ConsumerRecord<String, String> record : records) {
                buffer.add(record);
            }
            if (buffer.size() >= batchSize) {
                for (ConsumerRecord<String, String> record : buffer) {
                    log.info("Pull Consumer - Получено сообщение: value = {}, offset = {}", record.value(), record.offset());
                    // Фиксируем смещения вручную после успешной обработки сообщения
                    commitOffset(consumer, record.topic(), record.partition(), record.offset());
                }
                buffer.clear();
            } //else {
        }
    } catch (WakeupException e) {
        log.warn("Потребление остановлено", e);
    } catch (Exception e) {
        log.error("Ошибка при потреблении сообщений", e);
    } finally {
        consumer.close(); // Закрываем потребителя
    }
}

Метод ручной фиксации коммитов
[source, java]

private void commitOffset(KafkaConsumer<String, String> consumer, String topic, int partition, long offset) {
    OffsetAndMetadata offsetAndMetadata = new OffsetAndMetadata(offset + 1L); // Смещение увеличивается на единицу после успешного прочтения
    Map<TopicPartition, OffsetAndMetadata> offsetsToCommit = new HashMap<>();
    offsetsToCommit.put(new TopicPartition(topic, partition), offsetAndMetadata);
    consumer.commitSync(offsetsToCommit);
}

[[PushKafkaConsumerService]] **PushKafkaConsumerService**: +
Пуш модель забирает по одному сообщению за раз. Активен со старта
[source, java]
@KafkaListener(topics = "my-topic", groupId = "example-group")
public void listen(ConsumerRecord<String, String> record) {
    log.info("Push Consumer - Получено сообщение: value = {}, offset = {}", record.value(), record.offset());
}

== Саппорт

[[MessageGenerate]] **MessageGenerateService**: +
При отправке запроса на "http://localhost:8080/generate" переводит флаг в состояние true метод начинает генерировать сообщения раз в 3 секунды. +
При повторной отправке запроса переводит флаг в состояние false
[source, java]

@Scheduled(fixedRate = 3000)
private void sendMessageGenerate() throws JsonProcessingException {
    if (!schedulerEnabled){
        return;
    }
    String serializedMessage = mapper.writeValueAsString(messageBuilder());
    kafkaTemplate.send("my-topic", serializedMessage);
}

Метод для переключения флага.
[source, java]

public void toggleScheduler() {
    schedulerEnabled = !schedulerEnabled;
}

[[MessageDto]] **MessageRequestDto**: +
ДТО для мапинга запросов
[source, java]
@Getter
@Builder
public class MessageRequestDto {
    private Message message;
    private String topic;
}

== Гайд

1. Запустить docker-compose.yml
2. Создать топик
3. Отправить запрос по адресу "localhost:8080/generate"

